dice_pool/bestiary/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from bestiary.forms import AbilityForm, AttackForm

admin.autodiscover()

urlpatterns = patterns('bestiary.views',
   url(r'^$', 							                                    'monsterListing',               		   name = "bestiary_monsterListing"),
   url(r'^create/$', 					                                 'editMonster',	 	                     name = "bestiary_createMonster"),
   url(r'^(?P<mon_id>\d+)/$', 			                              'monsterDetail', 		                  name = "bestiary_monsterDetail"),
   url(r'^(?P<mon_id>\d+)/edit$', 		                              'editMonster', 		                  name = "bestiary_editMonster"),
   url(r'^(?P<mon_id>\d+)/rebalance/$', 			                     'rebalanceMonster', 		               name = "bestiary_rebalanceMonster"),
   url(r'^(?P<mon_id>\d+)/ability/$',                                'editAbility', {'form': AbilityForm },	name = "bestiary_createAbility"),
   url(r'^(?P<mon_id>\d+)/attack/$', 	                              'editAbility', {'form': AttackForm },	name = "bestiary_createAttack"),
   url(r'^(?P<mon_id>\d+)/ability/(?P<ability_id>\d+)/$',            'editAbility', {'form': AbilityForm },	name = "bestiary_editAbility"),
   url(r'^(?P<mon_id>\d+)/attack/(?P<attack_id>\d+)/$', 	            'editAbility', {'form': AttackForm },	name = "bestiary_editAttack"),
   url(r'^(?P<mon_id>\d+)/attack/(?P<attack_id>\d+)/rebalance/$',    'rebalanceAttack',                     name = "bestiary_rebalanceAttack"),
)

dice_pool/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('base.views',
	url(r'^$',			'root',						name='site_index'),
) + patterns('',
    url(r'^admin/', 	include(admin.site.urls)),
    url(r'^bestiary/', 	include('bestiary.urls')),
) + staticfiles_urlpatterns()

dice_pool/bestiary/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django import forms
from django.forms import ModelForm
from bestiary import choices
from bestiary import helpers as bhelpers
import math, random

class ActiveDefinitionManager(models.Manager):
   def get_query_set(self):
      return super(ActiveDefinitionManager, self).get_query_set().filter(active=True)

class InactiveDefinitionManager(models.Manager):
   def get_query_set(self):
      return super(ActiveDefinitionManager, self).get_query_set().filter(active=False)

class Definition(models.Model):
   name = models.CharField(max_length=50)
   active = models.BooleanField(default=True)
   objects = ActiveDefinitionManager()
   all_objects = models.Manager()

   def __unicode__(self):
      if not self.active:
         return '%s (Inactive)' % self.name
      return '%s' % self.name
   
   class Meta:
      ordering = ['-active', 'name']
      abstract = True

class MonsterRole(Definition):
   hpBase = models.IntegerField()
   hpRatio = models.DecimalField("HP per level", max_digits=3, decimal_places=2)
   gibRatio = models.DecimalField("Chunky Salsa Number",max_digits=3, decimal_places=2, help_text="Percentage of health needed to be done in a single attack to kill the target outright")
   acModMin = models.IntegerField("AC Adjustment Minimum")
   acModMax = models.IntegerField("AC Adjustment Maximum")
   fortModMin = models.IntegerField("Fortitude Adjustment Minimum")
   fortModMax = models.IntegerField("Fortitude Adjustment Minimum")
   refModMin = models.IntegerField("Reflex Adjustment Minimum")
   refModMax = models.IntegerField("Reflex Adjustment Minimum")
   willModMin = models.IntegerField("Will Adjustment Minimum")
   willModMax = models.IntegerField("Will Adjustment Minimum")
   heavyHitter = models.BooleanField("Sacrifice accuracy for damage?") #For brutes, mostly.
   
   def __unicode__(self):
      return "%s" % self.name
      
   def save(self, *args, **kwargs):
      if self.acModMin >= self.acModMax:
         self.acModMin = self.acModMax - 3
      
      if self.fortModMin >= self.fortModMax:
         self.fortModMin = self.fortModMax - 3
      
      if self.refModMin >= self.refModMax:
         self.refModMin = self.refModMax - 3
      
      if self.willModMin >= self.willModMax:
         self.willModMin = self.willModMax - 3
      super(MonsterRole, self).save(*args, **kwargs)

class Monster(models.Model):
   name = models.CharField(max_length = 100)
   level = models.IntegerField()
   role = models.ForeignKey(MonsterRole)
   minion = models.BooleanField(verbose_name = 'Minion?')
   elite = models.BooleanField(verbose_name = 'Elite?')
   solo = models.BooleanField(verbose_name = 'Solo?')
   initiative = models.IntegerField(verbose_name = 'Initiative')
   speed = models.IntegerField(verbose_name = 'Speed')
   hp = models.IntegerField(verbose_name = 'Health')
   gibHP = models.IntegerField(verbose_name = 'Insta-gib HP')
   ac = models.IntegerField(verbose_name = 'Armor Class')
   fortitude = models.IntegerField(verbose_name = 'Fortitude')
   reflex = models.IntegerField(verbose_name = 'Reflex')
   will = models.IntegerField(verbose_name = 'Will')
   acAtkBase = models.IntegerField(verbose_name = 'Base Attack Bonus vs. AC')
   nacAtkBase = models.IntegerField(verbose_name = 'Base Attack Bonus vs. NAD')
   eDC = models.IntegerField(verbose_name = 'Easy DC')
   mDC = models.IntegerField(verbose_name = 'Medium DC')
   hDC = models.IntegerField(verbose_name = 'Hard DC')
    
   def __unicode__(self):
      output = "Lvl. %s %s" % (self.level, self.name)
      role = " ("
      if self.elite:
         role += "Elite "
      
      if self.solo:
         role += "Solo "
      
      role += self.role.__unicode__()
      
      if self.minion:
         role += " Minion"
      
      role += ")"
      output += role
      return output
   
   def __rebalance__(self):
      self.initiative = self.level * .60
      self.hp = bhelpers.hpCalc(self.level, self.role, self.minion, self.elite, self.solo)
      self.gibHP = bhelpers.gibCalc(self.hp, self.role.gibRatio, self.minion, self.elite, self.solo)
      self.ac = bhelpers.defenseCalc(14, self.role.acModMin, self.role.acModMax, self.level, self.elite, self.solo)
      self.fortitude = bhelpers.defenseCalc(12, self.role.fortModMin, self.role.fortModMax, self.level, self.elite, self.solo)
      self.reflex = bhelpers.defenseCalc(12,self.role.refModMin, self.role.refModMax, self.level, self.elite, self.solo) 
      self.will = bhelpers.defenseCalc(12,self.role.willModMin, self.role.willModMax, self.level, self.elite, self.solo)     
      self.acAtkBase = random.randint(-1, 1) + self.level + 5
      self.nacAtkBase = random.randint(-1, 1) + self.level + 3
      self.eDC = 7 + round(self.level * .53)
      self.mDC = 12 + round(self.level * .53) + round(self.level/10)
      self.hDC = 17 + round(self.level *.64) + round(self.level/5)
      self.save()
      
      for attack in self.attack_set.all():
         attack.__rebalance__()

class Usage(Definition):
   limitedUsage = models.BooleanField("Limited")
   triggeredAction = models.BooleanField("Triggered?")
 
class PowerBase(models.Model):
   name = models.CharField(max_length=70, blank=True, null=True)
   monster = models.ForeignKey(Monster)
   usage = models.ForeignKey(Usage)
   action = models.CharField(max_length=2,choices=choices.ACTION)
   range = models.IntegerField()#0 for Personal, 1 for Melee
   area = models.IntegerField()#0 for Single Target, 1 for Burst/Blast 1, etc. 
   bloodiedLimit = models.BooleanField("Only usable when bloodied?")
   isRanged = models.BooleanField("Considered a Ranged Attack?")
   isPassive = models.BooleanField("A passive ability?")
   oaFlag = models.BooleanField("Provokes Opportunity Attack?")
   aura = models.BooleanField("Is an Aura?")
   effect = models.CharField(max_length=150,blank=True,null=True)
   aftereffect = models.CharField(max_length=150,blank=True,null=True)
   trigger = models.CharField(max_length=150,blank=True,null=True)
   
   def __unicode__(self):
      return "%s (%s %s power)" % (self.name, self.monster, self.usage)

   def atkRangeDisplay(self):
      str = "" 

      if self.aura:
         str = "Aura %s" % self.area

      elif self.area == 0:
         if self.range == 0:
            str = "Personal"
         else:
            if self.isRanged:
               str = "Ranged %s" % self.range
            else:
               str = "Melee / Touch" if self.range == 1 else "Reach %s" % self.range
      else:
         if self.range == 0:
            str = "Close Burst %s" % self.area
         elif self.range == 1:
            str = "Close Blast %s" % self.area
         else:
            str = "Area Burst %s in %s" % (self.area, self.range)
      if self.oaFlag:
         str += " (Provokes OA)"

      return str
   
   def atkUsageDisplay(self):
      str = "Passive" if self.isPassive else "%s -- %s" % (self.usage, self.get_action_display())
      
      if self.bloodiedLimit:
         str += " (Usable only when bloodied)"
      return str 

   class Meta:
      abstract = True

class Ability(PowerBase):
   pass

class Attack(PowerBase):
   attackBonus = models.IntegerField()
   targetDefense = models.CharField(max_length=1,choices=choices.DEFENSES,verbose_name='Target defense') 
   averageDamage = models.IntegerField()
   damageLine = models.CharField(max_length=150)
   multiStrike = models.BooleanField(verbose_name="Multiple attacks?:")
   onHit = models.CharField(max_length=150,blank=True,null=True, verbose_name="On hit:")
    
   def __unicode__(self):
      return "%s (%s %s)" % (self.name, self.usage, self.action)
   
   def __rebalance__(self):
      self.attackBonus = bhelpers.toHit(self.monster,self.range, self.area, self.isRanged, self.targetDefense)
      hasEffect = True if self.effect or self.aftereffect or self.onHit else False  
      self.averageDamage = bhelpers.averageDamage(self.monster, self.monster.role.heavyHitter, self.range,self.area,self.usage.limitedUsage, self.bloodiedLimit, self.multiStrike,hasEffect)
      self.damageLine = bhelpers.damageToDice(self.averageDamage,self.monster.minion,self.onHit)
      self.save()
    

dice_pool/bestiary/forms.py
from django.core.exceptions import ValidationError
from django.db import models
from django import forms
from bestiary import choices
from bestiary import models as mcm
from bestiary import helpers as bhelpers
import math, random

class MonsterForm(forms.ModelForm):
   def save(self, *args, **kwargs):
      record = super(MonsterForm, self).save(commit=False, *args, **kwargs)
      if not self.instance.id:   
         random.seed()
         record.initiative = record.level*.60
         record.hp = bhelpers.hpCalc(record.level, record.role, record.minion, record.elite, record.solo)
         record.gibHP = bhelpers.gibCalc(record.hp, record.role.gibRatio, record.minion, record.elite, record.solo)
         
         #Calculate our defenses
         record.ac = bhelpers.defenseCalc(14, record.role.acModMin, record.role.acModMax, record.level, record.elite, record.solo)
         record.fortitude = bhelpers.defenseCalc(12, record.role.fortModMin, record.role.fortModMax, record.level, record.elite, record.solo)
         record.reflex = bhelpers.defenseCalc(12,record.role.refModMin, record.role.refModMax, record.level, record.elite, record.solo) 
         record.will = bhelpers.defenseCalc(12,record.role.willModMin, record.role.willModMax, record.level, record.elite, record.solo)
         
         #Attack bonuses
         record.acAtkBase = random.randint(-1, 1) + record.level + 5
         record.nacAtkBase = random.randint(-1, 1) + record.level + 3
         
         #Skill DC for opposed checks (Save on rolls)
         record.eDC = 7 + round(record.level * .53)
         record.mDC = 12 + round(record.level * .53) + round(record.level/10)
         record.hDC = 17 + round(record.level *.64) + round(record.level/5)
      record.save()
   
   class Meta:
      model = mcm.Monster
      fields = ('name', 'level', 'role', 'minion', 'elite', 'solo', 'speed')

class AbilityForm(forms.ModelForm):
   
   def __init__(self, monster, *args, **kwargs):
      self.monster = monster
      super(AbilityForm, self).__init__(*args, **kwargs)    

   def clean(self):
      range = self.cleaned_data.get('range')
      area = self.cleaned_data.get('area')
      
      if range < 0:
         raise forms.ValidationError("Range minimum is 0.")
      
      if area < 0:
         raise forms.ValidationError("Area minimum is 0.")
      
      return self.cleaned_data 
        
   def save(self, *args, **kwargs):
      record = super(AbilityForm, self).save(commit=False,*args,**kwargs)
      #Brand new, needs to be processed.
      if not self.instance.id:   
         record.monster = self.monster
      record.save()

   class Meta:
      model = mcm.Ability
      exclude = ['monster']

class AttackForm(forms.ModelForm):
   
   def __init__(self, monster, *args, **kwargs):
      self.monster = monster
      super(AttackForm, self).__init__(*args, **kwargs)    

   def clean(self):
      range = self.cleaned_data.get('range')
      area = self.cleaned_data.get('area')
      
      if range < 0:
         raise forms.ValidationError("Range minimum is 0.")
      
      if area < 0:
         raise forms.ValidationError("Area minimum is 0.")
      
      return self.cleaned_data 
        
   def save(self, *args, **kwargs):
      record = super(AttackForm, self).save(commit=False,*args,**kwargs)
      #Brand new, needs to be processed.
      if not self.instance.id: 
         record.monster = self.monster
         record.attackBonus = bhelpers.toHit(record.monster,record.range, record.area, record.isRanged, record.targetDefense)
         hasEffect = True if record.effect or record.aftereffect or record.onHit else False  
         #For calculations and short hand if combat drags on.
         record.averageDamage = bhelpers.averageDamage(record.monster, record.monster.role.heavyHitter, record.range,record.area,record.usage.limitedUsage, record.bloodiedLimit, record.multiStrike,hasEffect)
         record.damageLine = bhelpers.damageToDice(record.averageDamage,record.monster.minion,record.onHit)
      record.save()

   class Meta:
      model = mcm.Attack
      exclude = ['monster', 'attackBonus', 'damageLine', 'averageDamage']

dice_pool/bestiary/views.py
from django.contrib import messages
from django.shortcuts import render_to_response, get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from bestiary import models as mcm 
from bestiary import forms as mcf
import math, random, unicodedata

def monsterListing(request):
   monster_list = mcm.Monster.objects.all().order_by('level')
   return render(request, 'bestiary/monsterList.html', {'monster_list': monster_list})
   
def monsterDetail(request, mon_id):
   try:
      monster = get_object_or_404(mcm.Monster, id=mon_id)
   except mcm.Monster.DoesNotExist:
      messages.error(request, "Not a valid monster")
      return redirect(reverse('bestiary_monsterListing'))
   return render(request, 'bestiary/monsterDetail.html', {'mon': monster})

def editMonster(request, mon_id=None):
   monster = None
   if mon_id:
	   monster = mcm.Monster.objects.get(id=mon_id)
   
   form = mcf.MonsterForm(request.POST or None, instance=monster)
   if form.is_valid():
      form.save()
      return redirect(reverse('bestiary_monsterListing'))
   return render(request, 'bestiary/editMonster.html', {'form': form,})

def editAbility(request,mon_id,form=None,attack_id=None, ability_id=None):
   try:   
      monster = mcm.Monster.objects.get(id=mon_id)
   except mcm.Monster.DoesNotExist:
      messages.error(request, "Not a valid monster.")
      return redirect(reverse('bestiary_monsterListing'))
   
   refObj=None 
   
   try:
      if attack_id:
         refObj = mcm.Attack.objects.get(id=attack_id)
      if ability_id:
         refObj = mcm.Ability.objects.get(id=ability_id)
   except mcm.Attack.DoesNotExist:
      messages.error(request, "No valid attack referenced.")
      return redirect(reverse('bestiary_monsterDetail', args=[mon_id,]))
   except mcm.Ability.DoesNotExist:
      messages.error(request, "No valid ability referenced.")
      return redirect(reverse('bestiary_monsterDetail', args=[mon_id,]))
   
   reqForm = form(monster, data=request.POST or None, instance=refObj)
   if reqForm.is_valid():
      reqForm.save()
      return redirect(reverse('bestiary_monsterDetail', args=[mon_id,]))

   return render(request, 'bestiary/editAbility.html', {'form': reqForm, 'c': monster})

def rebalanceMonster(request, mon_id):
   try:   
      monster = mcm.Monster.objects.get(id=mon_id)
   except mcm.Monster.DoesNotExist:
      messages.error(request, "Not a valid monster.")
      return redirect(reverse('bestiary_monsterListing'))
   else:
      monster.__rebalance__()
      return redirect(reverse('bestiary_monsterDetail', args=[mon_id,]))

def rebalanceAttack(request, mon_id, attack_id):
   try:   
      attack = mcm.Attack.objects.get(id=attack_id)
   except mcm.Attack.DoesNotExist:
      messages.error(request, "Not a valid Attack.")
      return redirect(reverse('bestiary_monsterListing'))
   else:
      attack.__rebalance__()
      return redirect(reverse('bestiary_monsterDetail', args=[mon_id,]))


dice_pool/templates/bestiary/create.html
{% extends "panel.html" %}

{% block body %}
	<br />
	<br />
	{% if error_message %} <p><strong> {{ error_message }}</strong></p>{% endif %}
	<form action="." method="post">
		{% csrf_token %}	
		{{form.as_p}}
		
		<input type="submit" value="Create" />
	</form>	
	<br />
<a href="{% url 'bestiary_mon_listing' %}">Back to the Monster Listing</a>
{% endblock %}

dice_pool/templates/bestiary/detail.html
{% extends "panel.html" %}
{% block body %}
	<h1>{{ mon.name }}</h2>
	<p><FONT SIZE = 3><b>Level:</b></FONT> {{mon.level}}
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<FONT SIZE = 3><b>Role:</b></FONT> {% if mon.eliteFlag %} Elite {% endif %} {% if mon.soloFlag%} Solo {% endif %} {{mon.get_role_display}} {% if mon.minionFlag %} Minion {% endif %}
	<br /><br /><FONT SIZE = 2><b>Initiative</b></FONT> {{mon.init}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE = 2><b>Speed</b></FONT> {{mon.speed}}
	<br /><FONT SIZE = 2><b>HP</b></FONT> {{mon.hp}} / {{mon.suddenDmg}}
	<br /><FONT SIZE = 2><b>AC</b></FONT> {{mon.ac}}
	<br /><FONT SIZE = 2><b>Fortitude</b></FONT> {{mon.fort}}
	<br /><FONT SIZE = 2><b>Reflex</b></FONT> {{mon.ref}}
	<br /><FONT SIZE = 2><b>Will</b></FONT> {{mon.will}}
	
	<h2>Skill Opposition</h2>
	<ul>
		<li>Novice (Easy DC): {{mon.eDC}}</li>
		<li>Experienced (Medium DC): {{mon.mDC}}</li>
		<li>Master (Hard DC): {{mon.hDC}}</li>
	</ul>
	
	<h2>Attacks</h2>
	
	<p><FONT SIZE = 2><b>Base Attack Bonus vs. AC:</b></FONT> {{ mon.acAtk}}
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<FONT SIZE = 2><b>Base Attack Bonus vs. NAD:</b></FONT> {{ mon.nacAtk}}
	
	<br />
	{% for attack in mon.attack_set.all %}
		
		<h3><u>{{attack.name}}</u></h3>
		<b>Usage:</b> {{attack.get_action_display}} ({{attack.get_use_display}})
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<b>Range:</b> 
		{% ifequal attack.attackType 'SEL' %}
			Personal
			{%else%}
			{% ifequal attack.attackRange 0%}
				Personal
			{%else%}
				{{attack.get_attackType_display}} 
				{% ifequal attack.attackType 'SME' %}
					{% if attack.attackRange > 1 %}
						(Reach {{attack.attackRange}})
					{% endif %}
				{% else %}
				 	{{attack.attackRange}}
				{% endifequal %}

			{% endifequal %}
		{% endifequal %} <br />
		
		{% ifnotequal attack.attackType 'SEL' %}
			<b>Attack: +</b>{{attack.atkBonus}} vs. {{attack.get_tardef_display}} 
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<b>Damage:</b> {{attack.damage}}<br />
		{% endifnotequal %}
				
		{% if attack.effects %}<b>Additional Effects:</b> {{attack.effects}} {% endif %}
		<br />
	{% endfor %}
	<br />
	<a href="{% url 'bestiary_create_power' mon.id %}">Add a new power</a>
	<br /><br />
	<b>Note:</b> If adding effects to the attacks, remove one die of damage per effect.
	
	<p><p><a href="{% url 'bestiary_mon_listing' %}">Back to the Monster Listing</a>
	<p><p><a href="{% url 'bestiary_create_mon' %}">Add a new monster</a>
{% endblock %}

dice_pool/templates/bestiary/editMonster.html
{% extends "panel.html" %}

{% block body %}
	<br />
	<br />
	{% if error_message %} <p><strong> {{ error_message }}</strong></p>{% endif %}
	<form class="entryForm" action="." method="post">
		{% csrf_token %}	
		<div>
         <span>
            {{ form.name.label_tag }}
            {{ form.name }}
            {{ form.name.errors }}
         </span>
      </div>
      <div>
         <span>
            {{ form.level.label_tag }}
            {{ form.level }}
            {{ form.level.errors }}
         </span>
         <span>
            {{ form.role.label_tag }}
            {{ form.role }}
            {{ form.role.errors }}
         </span>
      </div>
      <div>
         <span>
            {{ form.speed.label_tag }}
            {{ form.speed }}
            {{ form.speed.errors }}
         </span>
      </div>
      <div>
         <span>
            {{ form.minion.label_tag }}
            {{ form.minion }}
            {{ form.minion.errors }}
         </span>
         <span>
            {{ form.elite.label_tag }}
            {{ form.elite }}
            {{ form.elite.errors }}
         </span>
		   <span>
            {{ form.solo.label_tag }}
            {{ form.solo }}
            {{ form.solo.errors }}
         </span>
      </div>
		<input type="submit" value="Submit" />
	</form>	
	<br />
<a href="{% url bestiary_monsterListing %}">Back to the Monster Listing</a>
{% endblock %}

dice_pool/templates/bestiary/mon_detail.html
{% extends "panel.html" %}
{% block body %}
	<h1>{{ mon.name }}</h2>
	<p><FONT SIZE = 3><b>Level:</b></FONT> {{mon.level}}
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<FONT SIZE = 3><b>Role:</b></FONT> {% if mon.elite %} Elite {% endif %} {% if mon.solo %} Solo {% endif %} {{ mon.role }} {% if mon.minion %} Minion {% endif %}
	<br /><br /><FONT SIZE = 2><b>Initiative</b></FONT> {{ mon.initiative }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE = 2><b>Speed</b></FONT> {{mon.speed}}
	<br /><FONT SIZE = 2><b>HP</b></FONT> {{mon.hp}} / {{mon.gibHP}}
	<br /><FONT SIZE = 2><b>AC</b></FONT> {{mon.ac}}
	<br /><FONT SIZE = 2><b>Fortitude</b></FONT> {{ mon.fortitude }}
	<br /><FONT SIZE = 2><b>Reflex</b></FONT> {{ mon.reflex }}
	<br /><FONT SIZE = 2><b>Will</b></FONT> {{ mon.will }}
	
	<h2>Skill Opposition</h2>
	<ul>
		<li>Novice (Easy DC): {{ mon.eDC }}</li>
		<li>Experienced (Medium DC): {{ mon.mDC }}</li>
		<li>Master (Hard DC): {{ mon.hDC }}</li>
	</ul>
	
   <h2>Abilities</h2>
   {% for ability in mon.ability_set.all %}
      <h3><u>{{ ability.name }}</u></h3>
		<b>Usage:</b> {{ ability.get_action_display }} -- {{ ability.usage }}{% if ability.bloodiedLimit %}(Usable only when bloodied){% endif %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<b>Range:</b> {% ability.atkRangeDisplay %}{% if ability.oaFlag %}(Provokes OA){% endif %}
		{% if attack.effect %}<b>Effect:</b> {{ attack.effect }} {% endif %}
      {% if attack.aftereffect %}<b>Aftereffect:</b> {{ attack.aftereffect }} {% endif %}
		<br />

   {% endfor %} 

	<h2>Attacks</h2>
	
	<p><FONT SIZE = 2><b>Base Attack Bonus vs. AC:</b></FONT> {{ mon.acAtkBase }}
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<FONT SIZE = 2><b>Base Attack Bonus vs. NAD:</b></FONT> {{ mon.nacAtkBase }}
	
	<br />
	{% for attack in mon.attack_set.all %}
		<h3><u>{{ attack.name }}</u></h3>
		<b>Usage:</b> {{ attack.get_action_display }} -- {{ attack.usage }}{% if attack.bloodiedLimit %}(Usable only when bloodied){% endif %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<b>Range:</b> {% attack.atkRangeDisplay %}{% if attack.oaFlag %}(Provokes OA){% endif %}
		<b>Attack: +</b>{{ attack.attackBonus }} vs. {{ attack.get_targetDefense_display }} 
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<b>Damage:</b> {{ attack.damageLine }}{% if attack.onHit %} {{ attack.onHit }}. {% endif %}<br />
		{% if attack.effect %}<b>Effect:</b> {{ attack.effect }} {% endif %}
      {% if attack.aftereffect %}<b>Aftereffect:</b> {{ attack.aftereffect }} {% endif %}
		<br />
	{% endfor %}
	<br />
	<br /><br />
	<b>Note:</b> If adding effects to the attacks, remove one die of damage per effect.
	
	<p><p><a href="{% url bestiary_mon_listing %}">Back to the Monster Listing</a>
	<p><p><a href="{% url bestiary_create_mon %}">Add a new monster</a>
{% endblock %}